### ISSUE TITLE
Height in percentage  

### ISSUE THREAD

**Issue by kauly** [flexmonster/pivot-react#1]
` <FlexmonsterReact.Pivot
      toolbar={false}
      report={reportDef}
      height="100%"
      licenseKey={process.env.FLEX_MONSTER}
    />
`
That code render a pivot with 100px of height.

**Comment by flexmonster** [comment]
Hello, 

 

Thank you for your question.

 

We would like to point out that the reason for this is that by setting the height to 100% Flexmonster takes up 100% of the parent element's size.

Here is a more detailed explanation: https://stackoverflow.com/questions/1575141/how-to-make-a-div-100-height-of-the-browser-window

 

Please see the following JSFiddle example: https://jsfiddle.net/flexmonster/jdek7pq3/

 

Here the html and body tags' height is set to 100% and as a result, the pivot takes up the expected amount of space.

 

Please let us know if you have further questions.

 

Best Regards,

 

Flexmonster Team

**Comment by kauly** [comment]
Thanks for the answer, problem solved.

**Comment by flexmonster** [comment]
Hello, 

We are glad to hear that the problem is solved.

Could you please specify if you are already a client of Flexmonster?
We need this information for our records.

Best Regards,

Flexmonster Team

**Comment by kauly** [comment]
Not yet, we are testing this library.
