### ISSUE TITLE
connectTo method

### ISSUE THREAD

**Issue by kauly** [flexmonster/pivot-react#2]
When using the connectTo method, a possible timestamp is added to the request url.
```
pivotRef.flexmonster.connectTo({
      "dataSourceType": "json",
      "filename": url,
      "requestHeader": {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${props.token}`
      }
    });
```
![pivotcon](https://user-images.githubusercontent.com/15254623/58819439-9d63cd00-8606-11e9-8cc0-3eec184e021a.png)

The problem is that query param, ?433..

**Comment by iansadovy** [comment]
Hello @kauly ,

Thank you for the question and sorry for not answering earlier.
Flexmonster is adding a timestamp as a query parameter to the `filename` URL to prevent browser caching and loading actual data every time.
We recommend checking the back-end code to allow query params in your API endpoint.

Also, you can post your question on the official [Flexmonster Forum](https://www.flexmonster.com/forum/) to get the answers faster.

Hope it helps.

Regards,
Ian
