### ISSUE TITLE
 Can't resolve 'react-flexmonster' 

### ISSUE THREAD

**Issue by SunnyXiao** [flexmonster/pivot-react#3]
Hello,  wo clone your project, and "cd typescript";
then  i run  "npm install " and "npm start"
it show the error " Can't resolve 'react-flexmonster' ",  why?

**Comment by flexmonsterteam** [comment]
Hello, 

 

Thank you for reaching out to us.

 

The fix for this issue is now available in the latest version (2.7.14) of Flexmonster.

You are welcome to update the component.

 

Please let us know if this helped to resolve the problem.

 

Best Regards,
Flexmonster Team
